### ISSUE TITLE
Extra unnecessary stuff in the package

### ISSUE THREAD

**Issue by domenic** [domenic/wpt-runner#7]
Maybe more of an npm bug than anything else... but, when I do `npm pack` after #6, I get some crap that isn't necessary (and isn't specified in the `files` field):

```
$ tar -tf wpt-runner-2.3.0.tgz
package/package.json
package/LICENSE.txt
package/README.md
package/bin/wpt-runner.js
package/lib/console-reporter.js
package/lib/wpt-runner.js
package/web-platform-tests/LICENSE.md
package/web-platform-tests/README.md
package/web-platform-tests/resources/LICENSE
package/web-platform-tests/resources/readme.md
package/web-platform-tests/resources/testharness.js
package/web-platform-tests/testharness_runner.html
package/web-platform-tests/tools/wptrunner/LICENSE
package/web-platform-tests/tools/wptrunner/README.rst
package/web-platform-tests/tools/wptrunner/wptrunner/testharness_runner.html
```

`yarn pack` does better, although it still includes `testharness_runner.html` and an empty `webidl2` directory:

```
$ tar -tf wpt-runner-v2.3.0.tgz
package
package/bin
package/lib
package/LICENSE.txt
package/package.json
package/README.md
package/web-platform-tests
package/bin/wpt-runner.js
package/lib/console-reporter.js
package/lib/wpt-runner.js
package/web-platform-tests/resources
package/web-platform-tests/testharness_runner.html
package/web-platform-tests/resources/testharness.js
package/web-platform-tests/resources/webidl2
package/web-platform-tests/resources/webidl2/lib
```

If someone wants to file bugs on the relevant package managers that'd be kinda nice...

**Comment by MattiasBuelens** [comment]
This is weird... I'm just going to dump my findings so far.

`npm pack` uses [`npm-packlist`](https://github.com/npm/npm-packlist) to retrieve the list of files that must be added to the tarball. The algorithm is described in [its `README`](https://github.com/npm/npm-packlist/blob/991cd69bd1fd8fc88dd47238587d2daf6e0057ad/README.md). The first step is: 
>1. If a `package.json` file is found, and it has a `files` list,
>   then ignore everything that isn't in `files`.  Always include the
>   readme, license, notice, changes, changelog, and history files, if
>   they exist, and the package.json file itself.

Following that logic, we should only have the files explictly listed in `files`, plus the always-included `package.json`, `LICENSE` and `README` files.

For some reason though, it seems like the algorithm is also traversing through `web-platform-tests` and `web-platform-tests/resources` according to these rules. As such, the `LICENSE` and `README` files are also added because of step 1.

The HTML files are added because they are "explicitly included" in [`web-platform-tests/.gitignore`](https://github.com/w3c/web-platform-tests/blob/3589b85af366d5c53bf03cfeb5e0ccb3ac2a38e9/.gitignore#L16) according to step 5:
> 5. Unless they're explicitly included (by being in a `files` list, or
>   a `!negated` rule in a relevant `.npmignore` or `.gitignore`),
>   always ignore certain common cruft files:

None of this makes sense though. I don't understand why nested `.gitignore` or `.npmignore` need to be traversed when we have a `files` entry in the top-level `package.json`. 😕

**Comment by MattiasBuelens** [comment]
I've created a [small repro case](https://github.com/MattiasBuelens/npm-pack-weirdness). If you `npm pack` that, you end up with:
```
package/package.json
package/index.js
package/vendor/a.js
package/vendor/b.js
package/vendor/README.md
```
I think what's happening is this:
1. `npm pack` sees `package.json` with a `files` list. It doesn't immediately add those files, instead it adds the following ignore rules:
```
*
!index.js
!index.js/**
!vendor/a.js
!vendor/a.js/**
```
1. It sees that `vendor/a.js` has multiple directory levels, so it starts traversing those directories.
1. While traversing `vendor/`, it automatically adds `vendor/README.md`
1. When it sees that there's no `vendor/.npmignore`, it treats `.vendor/gitignore` as if it were a `.npmignore`
1. When it sees `!b.js` in that `.gitignore`, it adds `vendor/b.js` to the package

I guess that `npm pack` is working correctly, I just think that it has weird rules:
* `.npmignore` in subdirectories can override `files` list in top-level `package.json` ([docs](https://docs.npmjs.com/files/package.json#files))
* `.gitignore` is used as `.npmignore` when the latter does not exist
* `!` rules in an ignore file are handled as additional files to be packaged

**Comment by MattiasBuelens** [comment]
A workaround could be to copy `/web-platform-tests/resources/testharness.js` to `/testharness.js` in an npm `prepare` script. That way, `npm pack` never needs to traverse `/web-platform-tests`, so it won't add these weird rules.

Alternative solutions:
* Add `.npmignore` files to `web-platform-tests`, or avoid using `!` rules in `.gitignore`. This would not make any sense: `web-platform-tests` is not an npm package, so it should not have to deal with npm stuff.
* Get npm to not add files from `!` rules from a `.gitignore`-as-a-`.npmignore` file. This would probably break someone else's project, so no way npm would accept such a change.
